app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
send_sms:
    path:     /sendsms
    defaults: { _controller: AppBundle:Default:SendSms }
acme_payment_prepare:
    path:     /prepare
    defaults: { _controller: AppBundle:Payment:prepare }
acme_payment_done:
    path:     /done
    defaults: { _controller: AppBundle:Payment:done }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"