# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_PREMIEUM : ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
                    pattern: ^/oauth/v2/token
                    security: false
        oauth_authorize:
                    pattern: ^/oauth/v2/
                    security: false
        api:
                    pattern: ^/                                # All URLs are protected
                    fos_oauth: true                            # OAuth2 protected resource
                    stateless: true                            # Do no set session cookies
                    anonymous: true                           # Anonymous access is not allowed
        main:
            pattern: ^/
            stateless: true
            form_login:
                use_referer: true
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            oauth:
                            resource_owners:
                                facebook:           "/connect/check-facebook"
                            login_path:        /login
                            failure_path:      /
                            oauth_user_provider:
                                                service: hwi_oauth.user.provider.fosub_bridge
            logout:       true
            anonymous:    true



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Client1, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }